---
title: "Interactive pMN Assay Report - Generated by AutoPlate"
output:
  html_document:
    code_folding: hide
    number_sections: TRUE
params:
  drm_model: NA
---

# Input

## Load R libraries
```{r}
library(dplyr)
library(plot.matrix)
library(viridis)
library(ggplot2)
library(drc)
library(rmarkdown)
library(knitr)
library(plotly)
```

## Title

```{r}
platelist_file <- "pmn_platelist.csv"
assay_df <- read.csv(platelist_file, header = TRUE, stringsAsFactors = FALSE, check.names = FALSE)
title <- paste(unique(assay_df$experiment_id), "- Bleed", unique(assay_df$bleed), "- Virus", unique(assay_df$virus))
title
```

## Let's take a look at the data

```{r, layout="l-body-outset"}
knitr::kable(head(assay_df, 3))
```

## Dimensions before exclusion

```{r}
paste0("Rows: ", dim(assay_df)[1], ", Columns: ", dim(assay_df)[2])
```

## Dimensions after exclusion

```{r}
data <- dplyr::filter(assay_df, exclude == FALSE)
paste0("Rows: ", dim(data)[1], ", Columns: ", dim(data)[2])
```

## Number of wells excluded

```{r}
dim(assay_df)[1] - dim(data)[1]
```

# Quality Control

## Average Virus + Cell Luminescence

```{r, layout="l-body-outset"}
plates <- sort(unique(assay_df$plate_number))
av_cell_lum <- lapply(plates, function(plate_n) mean(dplyr::filter(assay_df, (plate_number == plate_n) & (types == "c"))$rlu))
av_viral_lum <- lapply(plates, function(plate_n) mean(dplyr::filter(assay_df, (plate_number == plate_n) & (types == "v"))$rlu))
no_cell_wells <- lapply(plates, function(plate_n) sum(dplyr::filter(assay_df, (plate_number == plate_n))$types == "c"))
no_viral_wells <- lapply(plates, function(plate_n) sum(dplyr::filter(assay_df, (plate_number == plate_n))$types == "v"))
av_lum_df <- do.call(rbind, Map(data.frame,
  plate_number = plates,
  average_cell_luminescence = av_cell_lum,
  average_viral_luminescence = av_viral_lum,
  number_of_cell_wells = no_cell_wells,
  number_of_virus_wells = no_viral_wells
))
knitr::kable(av_lum_df)
```

## Heatmaps for The 96 Well Plate(s)

```{r}
plot_heatmap <- function(plate_number, assay_df, feature, title) {
  plate_df <- assay_df[assay_df$plate_number == plate_number, ]
  feature_list <- unlist(plate_df[[feature]], use.names = FALSE)
  vals <- matrix(feature_list, byrow = T, ncol = 12, nrow = 8)
  row.names(vals) <- LETTERS[1:8]
  # Set params for plot based on the feature
  features <- c("types", "sample_id", "dilution", "virus", "rlu", "neutralisation", "treatment", "experiment_id", "bleed", "exclude")
  fmt.cells <- c("%.5s", "%.5s", "%.5s", "%.5s", "%.0f", "%.0f", "%.5s", "%.5s", "%.5s", "%.5s")
  features <- do.call(rbind, Map(data.frame, features = features, fmt.cells = fmt.cells))
  fmt.cell <- as.character(features[feature, ]$fmt.cells)
  col <- if (feature %in% c("dilution", "rlu", "neutralisation")) viridis else rainbow
  side <- if (feature %in% c("sample_id", "treatment", "experiment_id", "bleed", "exclude")) 3 else 4
  # Generate heatmap plot
  plot(vals, col = col, fmt.cell = fmt.cell, main = paste("Plate", plate_number, title), key = list(side = side))
}

features <- c("Types", "Sample ID", "Dilution", "Virus", "RLU", "Neutralisation", "Treatment", "Experiment ID", "Bleed", "Exclude")

for (feature in features) {
  for (plate in plates) {
    plot_heatmap(plate, assay_df, gsub(" ", "_", tolower(feature), fixed = TRUE), feature)
  }
}
```

## Types boxplot

```{r}
boxplot_data <- data %>%
  dplyr::mutate(types = ifelse((types == "c"), "cell", types)) %>%
  dplyr::mutate(types = ifelse((types == "m"), "monoclonal antibody", types)) %>%
  dplyr::mutate(types = ifelse((types == "v"), "virus", types)) %>%
  dplyr::mutate(types = ifelse((types == "x"), "serum sample", types))
boxplot_data$plate_number <- as.factor(boxplot_data$plate_number)

types_boxplot <- ggplot2::ggplot(boxplot_data, aes(x = plate_number, y = rlu, colour = types)) +
  geom_boxplot() +
  geom_point(position=position_dodge(0.75)) +
  ylab("Raw luminescence value") +
  xlab("Plate number") +
  theme_classic() +
  ggtitle(title)
plotly::ggplotly(types_boxplot) %>% layout(boxmode = "group")
```

# Results

## Data Exploration

```{r}
data <- dplyr::filter(data, types %in% c("x", "m"))

data_exploration_plot <- ggplot2::ggplot(data, aes(x = dilution, y = neutralisation, colour = treatment)) +
  geom_point() +
  geom_smooth(se = F, span = 1) +
  facet_wrap(. ~ virus) +
  ylim(c(-100, 110)) +
  scale_x_continuous(trans = "log10") +
  theme_classic() +
  ylab("Neutralisation") +
  xlab("Dilution") +
  ggtitle(title)
plotly::ggplotly(data_exploration_plot)
```

## DRM model

```{r}
model <- eval(parse(text = paste("drc::drm(", params$drm_model, ")")))
params$drm_model
```

## Dose Response Curve(s)

```{r}
plot_drc <- function(data,virus_to_plot,drm_model) {
  # Filter to keep only one virus
  data <- dplyr::filter(data, virus == virus_to_plot)

  # Preprocessing
  data$sample_id <- unlist(data$sample_id)
  model <- eval(parse(text = paste("drc::drm(", drm_model, ")")))
  n <- 100
  new_dilution <- exp(seq(log(min(data$dilution)), log(max(data$dilution)), length.out = n))
  sample_ids <- unique(data$sample_id)
  new_data <- expand.grid(new_dilution, sample_ids)
  names(new_data) <- c("dilution", "sample_id")
  new_data$treatment <- data$treatment[match(new_data$sample_id, data$sample_id)]
  new_data$pred <- predict(model, newdata = new_data, )
  facets <- if(length(unique(data$virus))>1) c("treatment","virus") else c("treatment")

  # Generate plot
  drc_plot <- ggplot2::ggplot(new_data, aes(x = dilution, y = pred, colour = treatment, group = sample_id)) +
    geom_line() +
    geom_point(data = data, aes(y = neutralisation)) +
    facet_wrap(facets) +
    scale_x_continuous(trans = "log10") +
    theme_classic() +
    theme(strip.background = element_blank()) +
    ylab("Neutralisation") +
    xlab("Dilution") +
    ggtitle(paste(unique(data$experiment_id), "- Bleed", unique(data$bleed), "- Virus", unique(data$virus)))
  # plotly::ggplotly(drc_plot)
  return(drc_plot)
}

# Produce a seperate plot for each virus
for (virus_to_plot in unique(data$virus)) {
  drc_plot <- plot_drc(data,virus_to_plot,params$drm_model)
  plot(drc_plot)
}
```

## IC50 Boxplot

```{r}
ied <- as.data.frame(ED(model, 50, display = FALSE))
ied$sample_id <- gsub("e:|:50", "", row.names(ied))
ied$treatment <- data$treatment[match(ied$sample_id, data$sample_id)]
ied$plate_number <- data$plate_number[match(ied$sample_id, data$sample_id)]
ied$virus <- data$virus[match(ied$sample_id, data$sample_id)]
facets <- if(length(unique(data$virus))>1) c("virus") else NULL
control_median <- median(ied[tolower(ied$treatment) %in% tolower(c("PBS", "negative_control")),]$Estimate)
# Average Neutralisation
avied <- summarise(group_by(ied, treatment), av = median(Estimate))
ied_order <- avied$treatment[order(avied$av)]

knitr::kable(ied)

ic50_boxplot <- ggplot2::ggplot(ied, aes(x = treatment, y = Estimate, colour = treatment)) +
  geom_boxplot() +
  geom_point() +
  facet_wrap(facets) +
  scale_x_discrete(limits = ied_order) +
  ylab("Individual IC50 log10") +
  xlab("Treatment") +
  theme_classic() +
  ggtitle(title) +
  coord_flip() +
  geom_hline(yintercept=c(control_median), linetype="dotted", )
plotly::ggplotly(ic50_boxplot)
```

## Virus + Cell Boxplot

```{r}
boxplot_data <- dplyr::filter(boxplot_data, types %in% c("cell", "virus"))

cv_boxplot <- ggplot2::ggplot(boxplot_data, aes(x = types, y = rlu, colour = plate_number)) +
  geom_boxplot() +
  geom_point(position = position_dodge(0.75)) +
  scale_y_continuous(trans = "log10") +
  ylab("Log10 raw luminescence value") +
  xlab("Cell only or Virus only") +
  theme_classic() +
  ggtitle(title)
plotly::ggplotly(cv_boxplot) %>% layout(boxmode = "group")
```

# Session Info for Reproducibility

```{r}
sessionInfo()
```
